const gifObject = {
  '01d': 'https://media.giphy.com/media/u01ioCe6G8URG/giphy.gif',
  '02d': 'https://media.giphy.com/media/h0VzgrFX9AKXK/giphy.gif',
  '03d': 'https://media.giphy.com/media/4b8Oi4TXZDStG/giphy.gif',
  '04d': 'https://media.giphy.com/media/4b8Oi4TXZDStG/giphy.gif',
  '09d': 'https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif',
  '10d': 'https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif',
  '11d': 'https://media.giphy.com/media/8xY1YYpEZ4dws/giphy.gif',
  '13d': 'https://media.giphy.com/media/xUOxf8xUMPuM5mvtMA/giphy.gif',
  '50d': 'https://media.giphy.com/media/3ohhwg3O1TGRXHQYh2/giphy.gif',
  '01n': 'https://media.giphy.com/media/l41YvfeoWdnqBf7Fu/giphy.gif',
  '02n': 'https://media.giphy.com/media/p4hYyN944mkZq/giphy.gif',
  '03n': 'https://media.giphy.com/media/QkwvkJc83E12g/giphy.gif',
  '04n': 'https://media.giphy.com/media/QkwvkJc83E12g/giphy.gif',
  '09n': 'https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif',
  '10n': 'https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif',
  '11n': 'https://media.giphy.com/media/8xY1YYpEZ4dws/giphy.gif',
  '13n': 'https://media.giphy.com/media/xUOxf8xUMPuM5mvtMA/giphy.gif',
  '50n': 'https://media.giphy.com/media/3ohhwg3O1TGRXHQYh2/giphy.gif',
};